#!/bin/bash

. e2e-tests/setup

cat <<EOF >$CFG
{
"file-path": "fil",
"ref-path": "refs",
"blob-path": "blobs",
"old-path": "old"
}
EOF
cat $CFG
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "update.cfg",
"blob-path": "blobs",
"old-path": "old"
}
EOF
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "refs",
"blob-path": "blo",
"old-path": "old"
}
EOF
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "refs",
"blob-path": "blobs",
"old-path": "oldp"
}
EOF
run_and_verify 12 update $CFG
