#!/bin/bash

. e2e-tests/setup

cat <<EOF >$CFG
{
"file-path": "fil",
"ref-path": "refs",
"blob-path": "blobs",
"dup-path": "dup"
}
EOF
cat $CFG
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "update.cfg",
"blob-path": "blobs",
"dup-path": "dup"
}
EOF
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "refs",
"blob-path": "blo",
"dup-path": "dup"
}
EOF
run_and_verify 12 update $CFG

cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "refs",
"blob-path": "blobs",
"dup-path": "dupp"
}
EOF
run_and_verify 12 update $CFG


cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "refs",
"blob-path": "blobs",
"dup-path": "dup"
}
EOF
