#!/bin/bash

. e2e-tests/setup

X## "File is inside a .dot directory, which should be ignored."
cat <<HERE | tee /dev/tty | bash
mkdir x/files/.dot
echo "abc 123" >x/files/.dot/foo
HERE

run_and_verify 0 update $CFG
