#!/bin/bash

set -x -e

rm -fr gocov-datafiles
mkdir gocov-datafiles

# Run unit tests.
# go test ./... -cover -args -test.gocoverdir=$PWD/gocov-datafiles

# Run e2e tests
go build --cover -o . ./...
./test $1

# Process the coverage data
go tool covdata textfmt -i=gocov-datafiles -o=gocov.txt
go tool cover -html=gocov.txt -o=gocov.html
# Why 25-, it needs to be a multiple of 8 +1 so tabs work...
go tool covdata func -i=gocov-datafiles | cut -b 25-
go tool covdata percent -i=gocov-datafiles | cut -b 25-

rm -fr gocov-datafiles gocov.txt

echo "See gocov.html for a colorized view of the actual code."
