#!/bin/bash

set -x -e

go build --cover -o . ./...

rm -fr gocov-datafiles
mkdir gocov-datafiles

./test

go tool covdata textfmt -i=gocov-datafiles -o=gocov.txt
go tool cover -html=gocov.txt -o=gocov.html
# Why 25-, it needs to be a multiple of 8 +1 so tabs work...
go tool covdata func -i=gocov-datafiles | cut -b 25-
go tool covdata percent -i=gocov-datafiles | cut -b 25-

rm -fr gocov-datafiles gocov.txt

echo "See gocov.html for a colorized view of the actual code."
