#!/bin/bash

for x in "e2e-tests/*$1*"; do
    echo "#####################"
    echo "$x"

    # Run test
    $x

    if [ "$?" -ne 0 ]; then
        echo
        echo "Failed $x"
        exit 1
    fi

done

rm -fr e2etmp
