#!/bin/bash

for x in e2e-tests/*/*; do
    if [ ! -x "$x" ]; then
        continue
    fi

    if [[ ! $x =~ $1 ]]; then
        echo "$x ...skipping"
        continue
    fi

    CLR='\033[0;36m' # PURPLE
    NC='\033[0m'     # No Color
    echo
    echo -e "${CLR}####   $x$NC"

    # Run test
    $x

    if [ "$?" -ne 0 ]; then
        CLR='\033[0;31m' # RED
        echo -e "${CLR}####$NC   $x   ${CLR}FAILED$NC"
        echo
        exit 1
    fi

    CLR='\033[0;32m' # GREEN
    echo -e "${CLR}####   $x$NC"
    echo
done

rm -fr x/
