#!/bin/bash

for x in e2e-tests/*/*; do
    if [ ! -x "$x" ]; then
        continue
    fi

    if [[ $x != *$1* ]]; then
        echo "$x ...skipping"
        continue
    fi

    echo "#####################"
    echo "$x"

    # Run test
    $x

    if [ "$?" -ne 0 ]; then
        echo
        echo "Failed $x"
        exit 1
    fi

    echo "$x"
    echo "#####################"

    # Uncomment this if you want to walk through each test output.
    # read z
done

rm -fr x/
