#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG

X## "Create invalid blob - really short name since that once caused a problem."
set -x
echo "a" >>x/blobs/a
set +x

run_and_verify 11 fsck $CFG
