#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG

X## "Create a blob that doesn't match it's name"
set -x
mv x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419a \
    x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419b
set +x

run_and_verify 11 fsck $CFG
run_and_verify 11 restore --file-path=$PWD/x/files2 $CFG
