#!/bin/bash

. e2e-tests/setup

X## "Invalid blob name - really short name since that once caused a problem."
rf x/blobs/a echo a
run 11 fsck $CFG

X## "Valid blob name, invalid checksum."
rf x/blobs/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa echo a
run 11 fsck $CFG
