#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "This will corrupt the blob"
rf x/files/foo echo a
run_and_verify 11 status $CFG
# TODO: This is a very scary looking panic...
run_and_verify 2 update $CFG
run_and_verify 11 fsck $CFG
