#!/bin/bash

. e2e-tests/setup

X## "Create an invalid ref file."
rf x/refs/corrupt echo a

run_and_verify 11 fsck $CFG
run_and_verify 11 restore --file-path=$PWD/x/files2 $CFG
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
run_and_verify 0 update $CFG
run_and_verify 0 fsck $CFG
