#!/bin/bash

. e2e-tests/setup

rf x/files/foo echo abc
runq update $CFG

X## "Create invalid ref."
cat <<HERE >x/refs/bad-sha
{
 "sha256": "c5d982dc040081e09cad25209fed928b334a21fb2ff34db5202178a7b1a81988",
 "unixnano": 1749858394741289104
}
HERE
rx cat x/refs/bad-sha
run 11 fsck $CFG
run 10 update $CFG

X## "Create invalid ref."
cat <<HERE >x/refs/bad-sha
{
 "sha256": "c5d98",
 "unixnano": 1749858394741289104
}
HERE
rx cat x/refs/bad-sha
run 11 fsck $CFG
