#!/bin/bash

. e2e-tests/setup

X## "Create an invalid ref file."
rf x/refs/corrupt echo a

run 11 fsck $CFG
run 11 restore --file-path=$PWD/x/files2 $CFG
run 10 status $CFG
run 10 update $CFG
run 0 update $CFG
run 0 fsck $CFG
