#!/bin/bash

. e2e-tests/setup

# This config is very dangerous, make sure this doesn't work.
cat <<EOF >$CFG
{
"file-path": "files",
"ref-path": "files",
"blob-path": "blobs",
"old-path": "old"
}
EOF

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg

# Thankfully status complains bitterly about this setup.
run 11 status $CFG

# Thankfully fsck complains bitterly about this setup.
run 11 fsck $CFG

# WARNING! This succeeds, in a horrible way. It just deleted all the users
#       data, well, thankfully it actually likely moved it to the /old/ directory.
# PLEASE be careful setting up your config!!
run 10 update $CFG
