#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Extra valid blobs are okay"
set -v
echo "abc 125" >x/blobs/bb964bb682d701aad340ab78c677e597fa8fc33df131c8b48f5b951c43d73338
set +v
echo

run 0 fsck $CFG
run 0 status $CFG

X## "Duplicate refs are okay."
set -v
cp x/refs/foo x/refs/cp_of_foo
set +v
echo

run 0 fsck $CFG
run 10 status $CFG
