#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
mkdir x/files/d
echo "abc 123" >x/files/d/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Removing file 'foo'"
set -v
rm x/files/d/foo
set +v
echo

# Make sure things are tidy.
rm -fr x/old/*
run 10 update $CFG

X## "Validating 'old' storage is correct."
set -v
cat <<EOF | diff <(cd x/old/* && find . -type f -printf "%p\n") -
./refs/d\\foo
./blobs/c5d982dc040081e09cad25209fed928b334a21fb2ff34db5202178a7b1a8199b
EOF
