#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Create duplicate ref"
set -v
cp x/refs/foo x/refs/cp_of_foo
set +v
echo

run 10 status $CFG
run 10 update $CFG
# TODO: find more standard way to test.
if [ -f x/refs/cp_of_foo ]; then
    echo "This file shouldn't exist"
    exit 1
fi
