#!/bin/bash

. e2e-tests/setup

set -v
echo "abc 123" >x/files/boo
echo "abc 123" >x/files/foo
ln x/files/foo x/files/aoo
set +v
echo

run 10 update $CFG

set -v
diff x/old/2*/dup/boo x/files/boo
set +v
echo

validate
