#!/bin/bash

set -e -x

function warn() {
    echo "$1"
    exit 1
}

TB=./toobig

rm -fr x

mkdir x
mkdir x/{data,blobs,git,dup,data2,blobs2,git2}

cat << EOF > x/update.cfg
{
"data_path": "data",
"git_path": "git",
"blob_path": "blobs",
"dup_path": "dup"
}
EOF
