#!/bin/bash

mkdir x/files-validate

cat <<EOF >x/validate.cfg
{
"file_path": "files-validate",
"ref_path": "refs",
"blob_path": "blobs",
"dup_path": "dup"
}
EOF

$TB restore x/validate.cfg

diff -r x/files x/files-validate
