#!/bin/bash

mkdir e2etmp/data-validate

cat << EOF > e2etmp/validate.cfg
data_path: data-validate
git_path: git
blob_path: blobs
dup_path: dup
EOF

$TB restore e2etmp/validate.cfg

diff -r e2etmp/data e2etmp/data-validate
