#!/bin/bash

mkdir x/data-validate

cat <<EOF >x/validate.cfg
{
"file_path": "data-validate",
"ref_path": "refs",
"blob_path": "blobs",
"dup_path": "dup"
}
EOF

$TB restore x/validate.cfg

diff -r x/data x/data-validate
