#!/bin/bash

. e2e-tests/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "This will corrupt the blob"
set -x
echo abc 125 >x/files/foo
set +x

# TODO:v3 Status should catch this error!
run_and_verify 10 status $CFG
run_and_verify 11 update $CFG
run_and_verify 11 fsck $CFG
