#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "This will corrupt the blob"
set -v
echo "abc 125" >x/files/foo
set +v
echo

# TODO:v3 Status should catch this error!
run_and_verify 10 status $CFG
run_and_verify 11 update $CFG
run_and_verify 11 fsck $CFG
