#!/bin/bash
# Verify that if a data file gets deleted that the matching
# git repo file is also deleted.

TB=./toobig

set -ev

rm -fr e2etmp

mkdir e2etmp
mkdir e2etmp/{data,blobs,git1,git2}

cat << EOF > e2etmp/update.cfg
data_path: data
git_path: git1
blob_path: blobs
EOF

cat << EOF > e2etmp/verify.cfg
data_path: data
git_path: git2
blob_path: blobs
EOF

echo abc 123 > e2etmp/data/foo
echo abc 124 > e2etmp/data/foo.jpg

$TB -v --dry-run update e2etmp/update.cfg

rm -f data/foo.jpg

$TB -v --dry-run update e2etmp/update.cfg

$TB -v --dry-run update e2etmp/verify.cfg

diff -r e2etmp/git1 e2etmp/git2
