#!/bin/bash
# Verify that if a data file gets deleted that the matching
# git repo file is also deleted.

TB=./toobig

set -ev

rm -fr e2etmp

mkdir e2etmp
mkdir e2etmp/{data,blobs,git1,git2}

cat << EOF > e2etmp/update.cfg
data_path: data
git_path: git1
blob_path: blobs
EOF

mkdir e2etmp/data/a
echo abc 123 > e2etmp/data/a/foo
echo abc 123 > e2etmp/data/a/foo.jpg

$TB update e2etmp/update.cfg
