#!/bin/bash

set -e

cd example

rm -fr blobs git data tada

mkdir blobs git data tada 

echo abc 123 > data/foo
echo abc 124 > data/foo.jpg

../toobig -v --dry-run update update.cfg

../toobig -v --dry-run restore restore.cfg

../toobig -v --dry-run fsck restore.cfg

diff -r data tada

tree
