#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/data/foo
echo abc 124 >x/data/foo.jpg

# update and then validate.
$TB update x/update.cfg
$TB fsck x/update.cfg

# The blob file referenced here doesn't exist.
cat <<HERE >x/git/no-sha.jpg
{
 "sha256": "c5d982dc040081e09cad25209fed928b334a21fb2ff34db5202178a7b1a81988",
 "unixnano": 1749858394741289104
}
HERE

exit_code=0
$TB fsck x/update.cfg || exit_code=$?
if [ $exit_code -ne 1 ]; then
    echo "Test failed with error code: $exit_code, Expected: 1."
    exit 1
fi
