#!/bin/bash
# Verify that if a data file gets deleted that the matching
# git repo file is also deleted.

TB=./toobig

set -ev

rm -fr e2etmp

mkdir e2etmp
mkdir e2etmp/{data1,data2,blobs,git1}

cat << EOF > e2etmp/update.cfg
data_path: data1
git_path: git1
blob_path: blobs
EOF

cat << EOF > e2etmp/restore.cfg
data_path: data2
git_path: git1
blob_path: blobs
EOF

echo abc 123 > e2etmp/data1/foo
echo abc 124 > e2etmp/data1/foo.jpg

$TB update e2etmp/update.cfg

rm -f data/foo.jpg

$TB restore e2etmp/restore.cfg

diff -r e2etmp/data1 e2etmp/data2
