#!/bin/bash

set -e

cd example

rm -fr blobs git data tada git2

mkdir blobs git data tada git2

echo abc 123 > data/foo
echo abc 124 > data/foo.jpg

../toobig -v --dry-run update update.cfg

rm -f data/foo.jpg

../toobig -v --dry-run update update.cfg

../toobig -v --dry-run update validate.cfg

diff -r git git2

tree
