#!/bin/bash

# If the same file is duplicated in data, make sure it is handled properly
# and that the dup ends up in the dup directory.

. e2e-tests/help/setup

mkdir e2etmp/data/a
echo abc 123 > e2etmp/data/a/foo
sleep 0.1
echo abc 123 > e2etmp/data/a/foo.jpg

$TB update e2etmp/update.cfg

diff e2etmp/git/a/foo e2etmp/git/a/foo.jpg

diff e2etmp/dup/a-foo.jpg - << EOF
abc 123
EOF

. e2e-tests/help/validate
