#!/bin/bash

. e2e-tests/help/setup

echo abc 123 > e2etmp/data/foo

$TB update e2etmp/update.cfg

# TODO: This suggests just relying on time isn't sufficient
# If we modify the file to quickly the timestamp hasn't changed.
sleep 0.2

echo abc 123 >> e2etmp/data/foo

# TODO: We should verify this exits for the correct reason.
$TB update e2etmp/update.cfg || exit 0

exit 1
