#!/bin/bash
# Verify that if a data file gets deleted that the matching
# git repo file is also deleted.

. e2e-tests/help/setup

echo abc 123 > e2etmp/data/foo
echo abc 124 > e2etmp/data/foo.jpg

$TB update e2etmp/update.cfg

rm -f data/foo.jpg

$TB update e2etmp/update.cfg

. e2e-tests/help/validate
