#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update x/update.cfg

touch x/files/foo
run_and_verify 1 status x/update.cfg
# TODO: Output is currently confusing for this test.

touch -d "2 hours ago" x/files/foo
run_and_verify 1 status x/update.cfg
