#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

touch x/files/foo
run_and_verify 1 status $CFG

touch -d "2 hours ago" x/files/foo
run_and_verify 1 status $CFG
