#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

# Extra "valid" blobs are okay
echo "abc 125" >x/blobs/bb964bb682d701aad340ab78c677e597fa8fc33df131c8b48f5b951c43d73338
run_and_verify 0 status $CFG
