#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update x/update.cfg

# Create a problem in the repo.
echo "a" >>x/blobs/a

run_and_verify 1 fsck x/update.cfg
