#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update x/update.cfg

# Modifying a file is a bad idea.
echo "abc 124" >>x/files/foo.jpg

run_and_verify 1 fsck x/update.cfg
