#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/data/foo
echo "abc 124" >x/data/foo.jpg

# Set our baseline for the test.
$TB update x/update.cfg
$TB fsck x/update.cfg

# Modifying a file is a bad idea.
echo "abc 124" >>x/data/foo.jpg

run_and_verify 1 fsck x/update.cfg
