#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG

# Modifying a file is a bad idea.
echo "abc 124" >>x/files/foo.jpg

run_and_verify 10 fsck $CFG
