#!/bin/bash

. e2e-tests/help/setup

echo "abc 123" >x/data/foo
echo "abc 124" >x/data/foo.jpg

# Set our baseline for the test.
$TB update x/update.cfg
$TB fsck x/update.cfg

# Create a blob that doesn't match it's name
mv x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419a \
    x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419b

run_and_verify 1 fsck x/update.cfg
