#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

# This isn't a valid ref file.
echo "abc 124" >>x/refs/corrupt.jpg

run_and_verify 10 fsck $CFG
