#!/bin/bash

. e2e-tests/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "Blob got removed somehow, update will fix it."
set -x
rm x/blobs/c5d98*
set +x

# TODO: This seems weird. Status should give an error 11... The repo is
# technically corrupt, but it can be fixed with an update.
run_and_verify 10 status $CFG
run_and_verify 11 fsck $CFG
run_and_verify 10 update $CFG
run_and_verify 0 fsck $CFG
validate
