#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Remove blob, update will fix it."
set -v
rm x/blobs/c5d98*
set +v
echo

# TODO: This seems weird. Status should give an error 11... The repo is
# technically corrupt, but it can be fixed with an update.
run_and_verify 10 status $CFG
run_and_verify 11 fsck $CFG
run_and_verify 11 restore -file-path=$PWD/x/files-validate $CFG

X## "Running the update that will fix it."
run_and_verify 10 update $CFG
run_and_verify 0 fsck $CFG
validate
