#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "Extra valid blobs are okay"
set -x
echo "abc 125" >x/blobs/bb964bb682d701aad340ab78c677e597fa8fc33df131c8b48f5b951c43d73338
set +x
run_and_verify 0 fsck $CFG
run_and_verify 0 status $CFG

X## "Duplicate files are okay."
set -x
cp x/refs/foo x/refs/cp_of_foo
set +x
run_and_verify 0 fsck $CFG
run_and_verify 10 status $CFG
