#!/bin/bash

. e2e-tests/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG
exit 1

X## "foo was touched"
set -x
touch x/files/foo
set +x
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG

X## "foo was updated into the past"
set -x
touch -d "2 hours ago" x/files/foo
set +x
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
