#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "Removing file 'foo'"
set -x
rm x/files/foo
set +x

# TODO: Are these ifs really the best way to do this?
if [ ! -f x/refs/foo ]; then exit 1; fi
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
if [ -f x/refs/foo ]; then exit 1; fi
validate
