#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Removing file 'foo'"
set -v
rm x/files/foo
set +v
echo

# TODO: Are these ifs really the best way to do this?
set -v
if [ ! -f x/refs/foo ]; then exit 1; fi
set +v
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
set -v
if [ -f x/refs/foo ]; then exit 1; fi
set +v
validate
