#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "foo was touched"
touch x/files/foo
run_and_verify 13 -v status $CFG
run_and_verify 13 -v update $CFG

X## "foo was updated into the past"
touch -d "2 hours ago" x/files/foo
run_and_verify 13 -v status $CFG
run_and_verify 13 -v update $CFG
