#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "foo was touched"
set -v
touch x/files/foo
set +v
echo

run_and_verify 10 status $CFG
run_and_verify 10 update $CFG

X## "foo was updated into the past"
set -v
touch -d "2 hours ago" x/files/foo
set +v
echo

run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
