#!/bin/bash

. e2e-tests/setup

X## "Add files."
rf x/files/update echo abc
rf x/files/time echo cde
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
# Just doing this because we have had bugs where files are constantly re-updated.
run_and_verify 0 update $CFG
validate

X## "Update file. Make sure to break the hardlink."
rx rm x/files/update
rf x/files/update echo xyz
run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
# Just validating doing the update fixed status.
run_and_verify 0 status $CFG
validate

X## "Update the file. Give it the same contents as another file."
rx rm x/files/update
rf x/files/update echo xyz
run_and_verify 10 update $CFG
X## "We forced a dup. Verify it doesn't require two updates."
run_and_verify 0 status $CFG
validate
