#!/bin/bash

. e2e-tests/setup

cat <<HERE | tee /dev/tty | bash
echo "abc 123" >x/files/foo
echo "abc 124" >x/files/foo.jpg
$TB update $CFG >/dev/null
HERE

X## "Update the file. Making sure to break the hardlink."
set -v
rm x/files/foo
echo "abc 125" >x/files/foo
set +v

run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
validate

X## "Modify the file. Make sure it updates even if the timestamp didn't change."
set -v
touch -r x/files/foo x/files/foo.jpg
rm x/files/foo
echo "abc 186" >x/files/foo
touch -r x/files/foo.jpg x/files/foo
set +v

run_and_verify 11 status $CFG
run_and_verify 10 update $CFG
validate
