#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
echo abc 124 >x/files/foo.jpg
$TB update $CFG

X## "Adding a new file."
set -x
echo abc 124 >x/files/extra
set +x

run_and_verify 10 status $CFG
run_and_verify 10 update $CFG
run_and_verify 0 fsck $CFG
. e2e-tests/help/validate
