#!/bin/bash

. e2e-tests/setup

mkdir x/files/d
echo "abc 123" >x/files/d/foo
echo "abc 124" >x/files/d/foo.jpg
$TB update $CFG

X## "Removing file 'foo'"
set -x
rm x/files/d/foo
set +x

run_and_verify 10 update $CFG

# find x/old -type f -printf "%-30p %-10s %t\n"
find x/old -printf "%-40p %y %n %i %-10s\n"

exit 3
