#!/bin/bash

. e2e-tests/setup

mkdir x/files/d
echo "abc 123" >x/files/d/foo
echo "abc 124" >x/files/d/foo.jpg
$TB update $CFG

X## "Removing file 'foo'"
set -x
rm x/files/d/foo
set +x

run_and_verify 10 update $CFG

set -x
cat <<EOF | diff <(cd x/old/2* && find . -type f -printf "%p\n") -
./refs/d\\foo
./blobs/c5d982dc040081e09cad25209fed928b334a21fb2ff34db5202178a7b1a8199b
EOF
set +x
