#!/bin/bash

# If a file is duplicated, make sure it is handled properly
# and that the dup ends up in the dup directory.

. e2e-tests/help/setup

mkdir x/files/a
echo abc 123 >x/files/a/foo
echo abc 123 >x/files/a/foo.jpg

$TB update $CFG

diff x/refs/a/foo x/refs/a/foo.jpg

diff x/dup/a-foo.jpg - <<EOF
abc 123
EOF

. e2e-tests/help/validate
