#!/bin/bash

# If a file is duplicated, make sure it is handled properly
# and that the dup ends up in the dup directory.

. e2e-tests/help/setup

mkdir x/files/a
echo abc 123 >x/files/a/foo
echo abc 123 >x/files/a/foo.jpg

run_and_verify 0 update $CFG

diff x/refs/a/foo x/refs/a/foo.jpg
diff x/dup/a-foo.jpg x/files/a/foo

. e2e-tests/help/validate
