#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/foo
run_and_verify 0 update $CFG
if [ ! -f x/refs/foo ]; then exit 1; fi

rm -f x/files/foo
run_and_verify 0 update $CFG
if [ -f x/refs/foo ]; then exit 1; fi
