#!/bin/bash

. e2e-tests/help/setup

echo abc 123 >x/files/boo
echo abc 123 >x/files/foo
ln x/files/foo x/files/aoo
run_and_verify 0 update $CFG

# Validate the set of files that was moved to the dup directory.
cat <<EOF | diff <(ls x/dup) -
boo
EOF

echo "abc 123" | diff x/dup/boo -

. e2e-tests/help/validate
