name: BuildAndTest

on: [push,pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Validate formatting
      run: test -z $(find . -name "*.go" | xargs gofmt -s -l)

    - name: go vet
      run: go vet ./...

    - name: Build
      run: go build -o . ./...

    - name: Test
      run: go test -v ./...

    - name: e2e Test
      run: ./test

    - name: Validate no diffs were generated
      run: test -z "$(git status --porcelain)"

    - name: Lint check
      run: go get -u golang.org/x/lint/golint; golint ./...

