name: BuildAndTest
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: go mod download

    - name: Validate go.mod is tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum

    - name: Validate formatting
      run: test -z $(find . -name "*.go" | xargs gofmt -s -l)

    - name: Build
      run: go build -o . ./...

    - name: Test
      run: go test -v ./...

    - name: e2e Test, validate no diffs
      run: |
        ./test
        git status
        test -z "$(git status --porcelain)"
